Add Terraform
dgarros/netdevops-survey pull request #82
Opened 2020-09-27 19:55 UTC by dgarros

I realized that we are missing Terraform as an option in few places.
I've seen multiple vendors releasing some Terraform modules so it will be interesting to track the adoption over time.

2020-09-27 21:05 UTC, fracaen commented
I like the idea of asking/tracking Terraform. It's an ok fit in the first question about config, but it seems to me like an odd fit under the software and validation questions.
How about we list it under the config question and in the end under "Which of the following tools are you interested in or have currently implemented?" Isn't that the best place to start tracking a tool's trend?

2020-09-27 21:17 UTC, fracaen requested changes
I like the idea of asking/tracking Terraform. 
It's an ok fit in the first question about config, but it seems to me like an odd fit under the software and validation questions.
How about we list it under the config question and in the end under "Which of the following tools are you interested in or have currently implemented?" -- which you did in another PR

2020-09-27 23:15 UTC, dgarros commented
Agreed

2020-09-28 01:06 UTC, fracaen approved these changes

2020-09-28 01:06 UTC, merged